languageCode = 'cs-CZ'
title = 'Můj blog'
timeout='120s'



[params.gpx]
  leafletJS = "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.8.0/leaflet-src.min.js"
  leafletGpxJS = "https://cdnjs.cloudflare.com/ajax/libs/leaflet-gpx/1.7.0/gpx.min.js"
  leafletCSS = "https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
  trackColors = ["blue", "darkblue", "purple"]
  attribution = "(c) <a href=\"https://www.openstreetmap.org/copyright\">OpenStreetMap</a> contributors"

